const VIETNAM_PROVINCES = [
    // Thành phố trực thuộc TW
    'Hà Nội',
    'TP. Hồ Chí Minh',
    'Đà Nẵng',
    'Hải Phòng',
    'Cần Thơ',
    // Miền Bắc
    'Bắc Giang',
    'Bắc Kạn',
    'Bắc Ninh',
    'Cao Bằng',
    'Điện Biên',
    'Hà Giang',
    'Hà Nam',
    'Hải Dương',
    'Hòa Bình',
    'Hưng Yên',
    'Lai Châu',
    'Lạng Sơn',
    'Lào Cai',
    'Nam Định',
    'Ninh Bình',
    'Phú Thọ',
    'Quảng Ninh',
    'Sơn La',
    'Thái Bình',
    'Thái Nguyên',
    'Tuyên Quang',
    'Vĩnh Phúc',
    'Yên Bái',
    // Miền Trung
    'Bình Định',
    'Bình Thuận',
    'Đắk Lắk',
    'Đắk Nông',
    'Gia Lai',
    'Hà Tĩnh',
    'Khánh Hòa',
    'Kon Tum',
    'Lâm Đồng',
    'Nghệ An',
    'Ninh Thuận',
    'Phú Yên',
    'Quảng Bình',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Trị',
    'Thanh Hóa',
    'Thừa Thiên Huế',
    // Miền Nam
    'An Giang',
    'Bà Rịa - Vũng Tàu',
    'Bạc Liêu',
    'Bến Tre',
    'Bình Dương',
    'Bình Phước',
    'Cà Mau',
    'Đồng Nai',
    'Đồng Tháp',
    'Hậu Giang',
    'Kiên Giang',
    'Long An',
    'Sóc Trăng',
    'Tây Ninh',
    'Tiền Giang',
    'Trà Vinh',
    'Vĩnh Long',
];

export default VIETNAM_PROVINCES;
